services:
 balloon:
   build:
     context: .
     dockerfile: Dockerfile
   deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
   ipc: host
   ports:
     - 8888:8888
   volumes:
     - ./config:/workspace/config
     - ./data:/workspace/data
     - ./outputs:/workspace/outputs
   working_dir: /workspace